FROM postgres:14.3
#might need to actually 

# FROM ubuntu:latest
# FROM library/postgres
# COPY init.sql /docker-entrypoint-initdb.d/init.sql
# MAINTAINER chrisl chlu@pdx.edu

# RUN apt-get -y update
# RUN apt-get -y upgrade
# RUN apt-get install -y build-essential

