version: '3'

services:
 postgres:
    container_name: postgres
    image: postgres:15-alpine
    restart: always
    ports:
      - "5432:5432" 
    volumes:
      - ./db:/var/lib/postgresql
      - ./db:/var/log/
      - ./db/initdb:/docker-entrypoint-initdb.d
    networks:
      - external_network
    environment:
      - POSTGRES_USER=user0
      - POSTGRES_PASSWORD=mysecretpassword
      - POSTGRES_DB=control-db
networks:
      external_network:
