# Use postgres/example user/password credentials
version: '3.1'

services:
  harasser_db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_DB: postgres_database_harasser
      POSTGRES_USER: user0 #doesn't allow login via database-1
    ports:
      - "5555:5555" 
  adminer:
    image: adminer
    restart: always
    ports:
      - 9090:9090

